<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by RAUGEY (INDEX EDUCATION) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.index-education.com/accueilENT" targetNamespace="http://www.index-education.com/accueilENT" elementFormDefault="qualified">
	<xsd:element name="Parent" type="TypeParent"/>
	<xsd:complexType name="TypeParent">
		<xsd:sequence>
			<xsd:element name="Eleve" type="TypeEleve" maxOccurs="unbounded"/>
			<xsd:element name="PageMessagerie" type="TypePageMessagerie" minOccurs="0"/>
			<xsd:element name="ICal" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="sessionENT" type="xsd:string"/>
		<xsd:attribute name="version" type="xsd:decimal"/>
	</xsd:complexType>
	<xsd:complexType name="TypeEleve">
		<xsd:sequence>
			<xsd:element name="Nom" type="xsd:string"/>
			<xsd:element name="Prenom" type="xsd:string"/>
			<xsd:element name="IdentifiantPronote" type="xsd:string"/>
			<xsd:element name="PageReleveDeNotes" type="TypePageReleveDeNotes" minOccurs="0"/>
			<xsd:element name="PageCompetences" type="TypePageCompetences" minOccurs="0"/>
			<xsd:element name="PageCahierDeTextes" type="TypePageCahierDeTextes" minOccurs="0"/>
			<xsd:element name="PageVieScolaire" type="TypePageVieScolaire" minOccurs="0"/>
			<xsd:element name="PagePronote" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="page" type="xsd:string" use="required"/>
					<xsd:attribute name="nom" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ICal" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TypePageReleveDeNotes">
		<xsd:sequence>
			<xsd:element name="Titre" type="xsd:string"/>
			<xsd:element name="Message" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Devoir" type="TypeDevoir" minOccurs="0" maxOccurs="5"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypePageCahierDeTextes">
		<xsd:sequence>
			<xsd:element name="Titre" type="xsd:string"/>
			<xsd:element name="Message" type="xsd:string" minOccurs="0"/>
			<xsd:element name="CahierDeTextes" type="TypeCahierDeTextes" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypePageCompetences">
		<xsd:sequence>
			<xsd:element name="Titre" type="xsd:string"/>
			<xsd:element name="Message" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Evaluation" type="TypeEvaluation" minOccurs="0" maxOccurs="5"/>
			<xsd:element name="Item" type="TypeItem" minOccurs="0" maxOccurs="5"/>
			<xsd:element name="Domaine" type="TypeDomaine" minOccurs="0" maxOccurs="5"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypePageVieScolaire">
		<xsd:sequence>
			<xsd:element name="Titre" type="xsd:string"/>
			<xsd:element name="Message" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Absence" type="TypeAbsence" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Retard" type="TypeRetard" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="PassageInfirmerie" type="TypePassageInfirmerie" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Punition" type="TypePunition" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Sanction" type="TypeSanction" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Observation" type="TypeObservation" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypePageMessagerie">
		<xsd:sequence>
			<xsd:element name="Titre" type="xsd:string"/>
			<xsd:element name="Message" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Discussions" type="TypeDiscussions" minOccurs="0"/>
			<xsd:element name="Informations" type="TypeInformations" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TypeDevoir">
		<xsd:sequence>
			<xsd:element name="Note" type="xsd:string"/>
			<xsd:element name="Bareme" type="xsd:string"/>
			<xsd:element name="Matiere" type="xsd:string"/>
			<xsd:element name="Date" type="xsd:date"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeCahierDeTextes">
		<xsd:sequence>
			<xsd:element name="Matiere" type="xsd:string"/>
			<xsd:element name="Date" type="xsd:date"/>
			<xsd:element name="ContenuDeCours" type="TypeContenuDeCours" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="TravailAFaire" type="TypeTravailAFaire" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeContenuDeCours">
		<xsd:sequence>
			<xsd:element name="Titre" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Categorie" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Descriptif" type="xsd:string" minOccurs="0"/>
			<xsd:element name="PieceJointe" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="SiteInternet" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeTravailAFaire">
		<xsd:sequence>
			<xsd:element name="Descriptif" type="xsd:string" minOccurs="0"/>
			<xsd:element name="PourLe" type="xsd:date"/>
			<xsd:element name="PieceJointe" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="SiteInternet" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeEvaluation">
		<xsd:sequence>
			<xsd:element name="Competence" type="xsd:string"/>
			<xsd:element name="Item" type="xsd:string"/>
			<xsd:element name="Intitule" type="xsd:string"/>
			<xsd:element name="Matiere" type="xsd:string"/>
			<xsd:element name="NiveauDAcquisition" type="TypeNiveauDAcquisition"/>
			<xsd:element name="Date" type="xsd:date"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeItem">
		<xsd:sequence>
			<xsd:element name="Competence" type="xsd:string"/>
			<xsd:element name="Intitule" type="xsd:string"/>
			<xsd:element name="Matiere" type="xsd:string" minOccurs="0"/>
			<xsd:element name="NiveauDAcquisition" type="TypeNiveauDAcquisition"/>
			<xsd:element name="Date" type="xsd:date" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeDomaine">
		<xsd:sequence>
			<xsd:element name="Competence" type="xsd:string"/>
			<xsd:element name="Intitule" type="xsd:string"/>
			<xsd:element name="Matiere" type="xsd:string" minOccurs="0"/>
			<xsd:element name="NiveauDAcquisition" type="TypeNiveauDAcquisition"/>
			<xsd:element name="Date" type="xsd:date" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeAbsence">
		<xsd:sequence>
			<xsd:element name="DateDebut" type="xsd:dateTime"/>
			<xsd:element name="DateFin" type="xsd:dateTime"/>
			<xsd:element name="EstOuverte" type="xsd:boolean"/>
			<xsd:element name="Justifie" type="xsd:boolean"/>
			<xsd:element name="Motif" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeRetard">
		<xsd:sequence>
			<xsd:element name="Date" type="xsd:dateTime"/>
			<xsd:element name="Justifie" type="xsd:boolean"/>
			<xsd:element name="Motif" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypePassageInfirmerie">
		<xsd:sequence>
			<xsd:element name="Date" type="xsd:dateTime"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypePunition">
		<xsd:sequence>
			<xsd:element name="Date" type="xsd:date"/>
			<xsd:element name="Nature" type="xsd:string"/>
			<xsd:element name="Matiere" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Motif" type="xsd:string"/>
			<xsd:element name="Circonstances" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeSanction">
		<xsd:sequence>
			<xsd:element name="Date" type="xsd:date"/>
			<xsd:element name="Nature" type="xsd:string"/>
			<xsd:element name="Motif" type="xsd:string"/>
			<xsd:element name="Circonstances" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Duree" type="xsd:integer" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeObservation">
		<xsd:sequence>
			<xsd:element name="Date" type="xsd:dateTime"/>
			<xsd:element name="Demandeur" type="xsd:string"/>
			<xsd:element name="Matiere" type="xsd:string"/>
			<xsd:element name="Observation" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeNiveauDAcquisition">
		<xsd:sequence>
			<xsd:element name="Genre" type="xsd:integer"/>
			<xsd:element name="Libelle" type="GenreNiveauDAcquisition"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:simpleType name="GenreNiveauDAcquisition">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Expert "/>
			<xsd:enumeration value="Acquis"/>
			<xsd:enumeration value="Presque acquis"/>
			<xsd:enumeration value="En cours d’acquisition"/>
			<xsd:enumeration value="Début d’acquisition"/>
			<xsd:enumeration value="Non acquis"/>
			<xsd:enumeration value="Absent"/>
			<xsd:enumeration value="Non évalué"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="TypeDiscussions">
		<xsd:sequence>
			<xsd:element name="NombreMessagesNonLus" type="xsd:integer"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="TypeInformations">
		<xsd:sequence>
			<xsd:element name="NombreInformationsNonLus" type="xsd:integer"/>
		</xsd:sequence>
		<xsd:attribute name="page" type="xsd:string"/>
	</xsd:complexType>
</xsd:schema>
